name: Create release files
on:
  push:
    branches:
      - main 
  pull_request:
jobs:
  compile-progs:
    name: Compile progs.dat
    runs-on: ubuntu-latest
    container: ghcr.io/progs-dump-dev/fteqcc-docker:main
    steps:
      - uses: actions/checkout@v3
      - name: Set up folder structure
        shell: bash
        run: |
          cd qc
          fteqcc64
      - name: Upload progs
        uses: actions/upload-artifact@v4
        with:
          name: progs-dat
          path: |
            progs.dat
            progs.lno
